{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "keycloak.fullname" .}}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: {{ .Values.keycloak.service.port }}
    targetPort: {{ .Values.keycloak.service.targetport }}

  selector:
    name: {{ template "keycloak.fullname" . }}
{{ end}}
