mespace: default

isTls: true
urlList:
  - "keycloak-testing.gada.io"

init_container:
  image: odise/busybox-curl
  imagePullPolicy: IfNotPresent

mysql:
  enabled: true
  repository: mysql
  tag: 8.0.30
  imagePullPolicy: Always
  env:
    MYSQL_ROOT_PASSWORD: "password"
    MYSQL_DATABASE: "keycloakdb"
    MYSQL_USER: "genny"
    MYSQL_PASSWORD: "password"
  service:
    port: 3306
    targetport: 3306

keycloak:
  enabled: true
  repository: gennyproject/keycloak
  tag: 19-quarkus 
  imagePullPolicy: Always
  env:
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: password 
    KC_PROXY: passthrough
    KEYCLOAK_LOGLEVEL: debug
    JAVA_OPTS_APPEND: "-Djava.awt.headless=true"
  service:
    port: 8080
    targetport: 8080
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 10m

nginx:
  enabled: true
  repository: k8s.gcr.io/ingress-nginx/controller
  tag: v1.0.0
  namespace: kube-system
  config:
    client-max-body-size: 100m
    custom-http-errors: "503"
    proxy-body-size: 100m
  revisionHistoryLimit: 3
  default_backend:
    repository: gcr.io/google_containers/defaultbackend
    tag: "1.0"
  service:
    type: NodePort
    port: 80
