{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nginx.fullname" . }}-credential
  namespace: {{ .Values.nginx.namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "secret/dh-param" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}
{{- end }}

