{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nginx-default_backend.fullname" . }}
  namespace: {{ .Values.nginx.namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"  
 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        name: {{ template "nginx-default_backend.fullname" . }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ template "nginx-default_backend.fullname" . }} 
        image: {{ .Values.nginx.default_backend.repository }}:{{ .Values.nginx.default_backend.tag }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports: 
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
      restartPolicy: Always
{{ end }}


