{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: {{ template "nginx.fullname" . }}-controller
  namespace: {{ .Values.nginx.namespace }} 
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec: 
  revisionHistoryLimit: {{ .Values.nginx.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template: 
    metadata: 
      labels:
        app: {{ template "fullname" . }}
        name: {{ template "nginx.fullname" . }}
    spec: 
      hostNetwork: true
      containers: 
        - args: 
            - /nginx-ingress-controller
            - --default-backend-service=$(POD_NAMESPACE)/{{ template "nginx-default_backend.fullname" . }}-svc
            - --configmap=$(POD_NAMESPACE)/{{ template "nginx.fullname" . }}-config
          env: 
            - name: POD_NAME
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.namespace
          image: {{ .Values.nginx.repository }}:{{ .Values.nginx.tag }}
          imagePullPolicy: IfNotPresent
          livenessProbe: 
            httpGet: 
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
          name: {{ template "nginx.fullname" .}}
          ports: 
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
          volumeMounts: 
            - mountPath: /etc/nginx-ssl/dhparam
              name: tls-dhparam-vol
      terminationGracePeriodSeconds: 120
      volumes: 
        - name: tls-dhparam-vol
          secret: 
            secretName: {{ template "nginx.fullname" . }}-credential
      restartPolicy: Always
{{ end }}
