{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx-default_backend.fullname" . }}-svc
  namespace: {{ .Values.nginx.namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "nginx-default_backend.fullname" . }} 
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: 8080
  type: {{ .Values.nginx.service.type }}

{{ end }}

