apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "mysql.fullname" . }}-volumes
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10G
  hostPath:
    path: /var/lib/mysql
    type: ""
  storageClassName: manual
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mysql.fullname" . }}-pvc-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}" 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: {{ template "mysql.fullname" . }}-volumes
